// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WifeGift.DataAccess.Contexts;

#nullable disable

namespace WifeGift.Migrations.UserData
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20260307172220_InitialUserData")]
    partial class InitialUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WifeGift.DataAccess.Models.Preference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Adjective")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adjective");

                    b.Property<Guid>("UserDataId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_data_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_preferences");

                    b.HasIndex("UserDataId")
                        .HasDatabaseName("ix_preferences_user_data_id");

                    b.ToTable("preferences", (string)null);
                });

            modelBuilder.Entity("WifeGift.DataAccess.Models.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_data");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_data_user_id");

                    b.ToTable("user_data", (string)null);
                });

            modelBuilder.Entity("WifeGift.DataAccess.Models.Preference", b =>
                {
                    b.HasOne("WifeGift.DataAccess.Models.UserData", "UserData")
                        .WithMany("Preferences")
                        .HasForeignKey("UserDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_preferences_user_data_user_data_id");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("WifeGift.DataAccess.Models.UserData", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
